version: "3.9"
services:
  api:
    image: nnee2810/book-store-api
    restart: on-failure:3
    environment:
      - PORT=${PORT}
    ports:
      - 80:${PORT}
    depends_on:
      - postgres
      - redis
      - rmq
    networks:
      - postgres-network
      - redis-network
      - rmq-network

  postgres:
    image: postgres:alpine
    restart: on-failure:3
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  redis:
    image: redis:alpine
    restart: on-failure:3
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - redis-network

  redisinsight:
    image: redislabs/redisinsight:1.13.1
    restart: on-failure:3
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis
    networks:
      - redis-network

  rmq:
    image: rabbitmq:3.9.29-management-alpine
    restart: on-failure:3
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq:/var/lib/rabbitmq
    networks:
      - rmq-network

volumes:
  postgres:
  redis:
  redisinsight:
  rmq:
networks:
  postgres-network:
  redis-network:
  rmq-network:
