version: "3.9"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - redis-network
  redisinsight:
    image: redislabs/redisinsight:1.13.1
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis
    networks:
      - redis-network
  rmq:
    image: rabbitmq:3.9.29-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_USER_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq:/var/lib/rabbitmq

volumes:
  postgres:
  redis:
  redisinsight:
  rmq:
networks:
  redis-network:
